#define NUM_ARGUMENTS 2
#define NUM_ARGUMENTS_FOR_RW 3

#define ONE_BYTE 1
#define SECTOR_SIZE 512

#define CLUSTER_UNUSED 0x00
#define CLUSTER_END 0xFF8
#define CLUSTER_LAST_FILE_SECTOR 0xFFF

#define VOL_LABEL_POS 43
#define VOL_LABEL_SIZE 11

#define ROOT_SECTOR 19
#define FAT_SECTOR 1

#define FAT_UNUSED 0x00
#define FAT_PREDEFINED_SECTORS 33
#define FAT_RESERVED_SECTORS 2

#define FILE_SIZE_POS_OFFSET 28
#define FILE_SIZE_SIZE 4

#define LONG_FILENAME 0x0F
#define FILENAME_POS_OFFSET 0
#define FILENAME_SIZE 8

#define EXTENSION_POS_OFFSET 8
#define EXTENSION_SIZE 3

#define EXTENSION_POS_OFFSET 8
#define EXTENSION_SIZE 3

#define CREATION_DATE_POS_OFFSET 16
#define CREATION_DATE_SIZE 2

#define CREATION_TIME_POS_OFFSET 14
#define CREATION_TIME_SIZE 2

#define ATTRIBUTES_POS_OFFSET 11
#define ATTRIBUTES_SIZE 1

#define DIR_EMPTY 0x00
#define DIR_UNUSED 0xE5
#define DIR_SYSTEM_FILE 0x04
#define DIR_VOLUME_LABEL 0x08
#define DIR_SUBDIRECTORY 0x10
#define DIR_SIZE 32
#define DIR_FIRST_CLUSTER_POS_OFFSET 26
#define DIR_FIRST_CLUSTER_SIZE 2

#define NUM_FAT_COPIES_POS 16
#define NUM_FAT_COPIES_SIZE 1

#define NUM_SECTORS_PER_FAT_POS 22
#define NUM_SECTORS_PER_FAT_SIZE 2

#define A_BYTE 8
#define ALL_8_BITS_ON 0xFF
#define UPPER_4_BITS_ON 0xF0
#define LOWER_4_BITS_ON 0x0F
